#!/usr/bin/env python3
"""Merge only a verified PR created by the Android download workflow."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from typing import Any


BRANCH = "automation/android-downloads"
BASE_BRANCH = "gh-pages"
BOT_LOGIN = "github-actions[bot]"
ALLOWED_FILES = {"android-studio.html", "android-emulator.html", "index.html"}
MAX_DIFF_LINES = 2000
CHECK_NAME = "Cloudflare Pages"
CHECK_APP = "cloudflare-workers-and-pages"
POLL_INTERVAL_SECONDS = 10
POLL_ATTEMPTS = 30


class MergeBlocked(RuntimeError):
    """The PR needs manual attention and must stay open."""


def _get_json(endpoint: str) -> Any:
    result = subprocess.run(["gh", "api", endpoint], check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


def _review_decision(repo: str, number: int) -> str | None:
    result = subprocess.run(
        ["gh", "pr", "view", str(number), "--repo", repo, "--json", "reviewDecision"],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)["reviewDecision"]


def _merge(repo: str, number: int, head_sha: str) -> None:
    subprocess.run(
        ["gh", "pr", "merge", str(number), "--repo", repo, "--merge", "--match-head-commit", head_sha],
        check=True,
    )


def _validate_pr(pr: dict[str, Any], files: list[dict[str, Any]], repo: str, head_sha: str) -> None:
    if pr["state"] != "open" or pr["draft"]:
        raise MergeBlocked("PR is not open and ready")
    if pr["user"]["login"] != BOT_LOGIN:
        raise MergeBlocked("PR author is not the GitHub Actions bot")
    if pr["base"]["repo"]["full_name"] != repo or pr["base"]["ref"] != BASE_BRANCH:
        raise MergeBlocked("PR base is not this repository's gh-pages branch")
    if (
        pr["head"]["repo"]["full_name"] != repo
        or pr["head"]["ref"] != BRANCH
        or pr["head"]["sha"] != head_sha
    ):
        raise MergeBlocked("PR head is not the commit generated by this workflow run")
    if not files or len(files) != pr["changed_files"] or len(files) > len(ALLOWED_FILES):
        raise MergeBlocked("PR files are missing or incomplete")
    if any(file["filename"] not in ALLOWED_FILES or file["status"] != "modified" for file in files):
        raise MergeBlocked("PR files escaped the generated-page allowlist")
    changed_lines = sum(file["additions"] + file["deletions"] for file in files)
    if changed_lines > MAX_DIFF_LINES:
        raise MergeBlocked(f"PR files exceed the {MAX_DIFF_LINES}-line limit")


def _checks_passed(checks: dict[str, Any]) -> bool:
    runs = checks["check_runs"]
    if checks["total_count"] != len(runs):
        raise MergeBlocked("PR check list is incomplete")
    if any(run["status"] == "completed" and run["conclusion"] != "success" for run in runs):
        raise MergeBlocked("A PR check failed or was cancelled")
    cloudflare_passed = any(
        run["name"] == CHECK_NAME
        and run["app"]["slug"] == CHECK_APP
        and run["status"] == "completed"
        and run["conclusion"] == "success"
        for run in runs
    )
    return cloudflare_passed and all(run["status"] == "completed" for run in runs)


def _validate_base_ref(repo: str, expected_sha: str) -> None:
    current = _get_json(f"repos/{repo}/git/ref/heads/{BASE_BRANCH}")
    if current["object"]["sha"] != expected_sha:
        raise MergeBlocked("The base branch changed since the pages were generated")


def merge_verified_pr(repo: str, number: int, head_sha: str, base_sha: str, *, attempts: int = POLL_ATTEMPTS) -> None:
    pr_endpoint = f"repos/{repo}/pulls/{number}"
    files_endpoint = f"{pr_endpoint}/files?per_page=100"

    _validate_pr(_get_json(pr_endpoint), _get_json(files_endpoint), repo, head_sha)
    _validate_base_ref(repo, base_sha)
    for attempt in range(attempts):
        checks = _get_json(f"repos/{repo}/commits/{head_sha}/check-runs?per_page=100&filter=latest")
        if _checks_passed(checks):
            break
        if attempt < attempts - 1:
            print(f"Waiting for {CHECK_NAME} on {head_sha} ({attempt + 1}/{attempts})", flush=True)
            time.sleep(POLL_INTERVAL_SECONDS)
    else:
        raise MergeBlocked(f"{CHECK_NAME} did not pass within the wait period")

    _validate_pr(_get_json(pr_endpoint), _get_json(files_endpoint), repo, head_sha)
    _validate_base_ref(repo, base_sha)
    if _review_decision(repo, number) not in (None, "APPROVED"):
        raise MergeBlocked("The PR requires review before merging")
    _merge(repo, number, head_sha)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--pr-number", required=True, type=int)
    parser.add_argument("--head-sha", required=True)
    parser.add_argument("--base-sha", required=True)
    args = parser.parse_args()
    try:
        merge_verified_pr(args.repo, args.pr_number, args.head_sha, args.base_sha)
    except (MergeBlocked, subprocess.CalledProcessError) as exc:
        print(f"Auto-merge stopped; PR remains open: {exc}", file=sys.stderr)
        return 1
    print(f"Merged Android download PR #{args.pr_number}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
